esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor a PowMr inverter"
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3

packages:
  inverter: !include modules/inverter.yaml

#  for using PZEM uncomment this line:  
#  pzem: !include modules/pzem.yaml

#  for debug uncomment this line:
#  debug: !include modules/debug.yaml

#  for inverter info sensors uncomment this line:
#  inverter-info: !include modules/inverter-info.yaml

#  changes for model POW-HVM10.2M-48V:
#  pow-hvm10.2m-48v: !include modules/pow-hvm10.2m-48v.yaml