text_sensor:

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    id: Machine_Type
    name: "Machine Type"
    icon: mdi:memory
    entity_category: diagnostic
    address: 4517
    register_type: holding
    response_size: 2
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t sensorIndex = swapBytes(modbus_controller::word_from_hex_str(x, 0));
      switch (sensorIndex) {
        case 0: return std::string("Solar Inverter");
        case 1: return std::string("Voltage regulator");
        default: return std::string(x);
      }

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    id: Battery_Piece
    name: "Battery Piece"
    icon: mdi:battery
    entity_category: diagnostic
    address: 4520
    register_type: holding
    response_size: 2
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t sensorIndex = swapBytes(modbus_controller::word_from_hex_str(x, 0));
      switch (sensorIndex) {
        case 0: return std::string("No Battery");
        case 1: return std::string("24V");
        case 2: return std::string("48V");
        default: return std::string(x);
      }

sensor:

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Main CPU version"
    icon: mdi:chip
    entity_category: diagnostic
    address: 4518
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Secondary CPU version"
    icon: mdi:chip
    entity_category: diagnostic
    address: 4519
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal output apparent power"
    entity_category: diagnostic
    unit_of_measurement: "VA"
    device_class: apparent_power
    address: 4521
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal output active power"
    entity_category: diagnostic
    unit_of_measurement: "W"
    device_class: power
    address: 4522
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal AC voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    device_class: voltage
    address: 4523
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal AC current"
    entity_category: diagnostic
    unit_of_measurement: "A"
    device_class: current
    address: 4524
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Rated battery voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    device_class: voltage
    address: 4525
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal output voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    device_class: voltage
    address: 4526
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal output frequency"
    entity_category: diagnostic
    unit_of_measurement: "Hz"
    device_class: frequency
    address: 4527
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Nominal output current"
    entity_category: diagnostic
    unit_of_measurement: "A"
    device_class: current
    address: 4528
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "ID1"
    icon: mdi:identifier
    entity_category: diagnostic
    address: 4531
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "ID2"
    icon: mdi:identifier
    entity_category: diagnostic
    address: 4532
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "ID3"
    icon: mdi:identifier
    entity_category: diagnostic
    address: 4533
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "ID4"
    icon: mdi:identifier
    entity_category: diagnostic
    address: 4534
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return swapBytes(x);
