sensor:
  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV 2 Voltage"
    id: pv2_voltage
    address: 4563
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      return swapBytes(x);
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV 2 Power"
    id: pv2_power
    address: 4564
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    lambda: |-
      return swapBytes(x);

  - platform: template
    name: "PV 2 Current"
    state_class: "measurement"
    device_class: current
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:solar-power
    lambda: |-
      return id(pv2_power).state / id(pv2_voltage).state;
